apiVersion: 1
deleteDatasources: []
datasources:
  - name: Prometheus
    access: proxy
    isDefault: true
    type: prometheus
    url: http://prometheus:9090/
  - name: Loki
    access: proxy
    isDefault: false
    type: loki
    url: http://loki:3100/