{
 "title": "Drift JIT Bot",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Filled Orders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "filled_orders_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Open Orders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "open_orders", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "uPNL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ch_user_unrealized_pnl", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "options": {
    "content": "<center>\n<h1>Drift JIT Bot</h1>\n<a href=\"https://github.com/0xperp/keeper-bots-v2\">github.com/0xperp/keeper-bots-v2</a><br/ >\nRead more about changes <a href=\"https://www.notion.so/adjacentresearch/Improved-JIT-Maker-Bot-8a9f831e5f884eb0897fbff74c71d896\">here</a> \n</center>"
   }
  },
  {
   "title": "Open Position Quote Asset Amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "open_position_quote_asset_amount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Position Quote Entry Amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "open_position_quote_entry_amount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Position Base Amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "open_position_base_asset_amount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Position Asset Amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "open_position_quote_asset_amount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unrealized Funding PNL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "ch_user_unrealized_funding_pnl", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unrealized PNL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "ch_user_unrealized_pnl", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Open Position Asks Amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    { "expr": "open_position_open_asks_amount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Open Position Bids Amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    { "expr": "open_position_open_bids_amount", "legendFormat": "__auto" }
   ]
  }
 ]
}